/**
 * WeaponDB — 武器資料庫
 * 武器影響 ATK 加成、命中率，並有耐久度系統
 */

const WEAPON_DB = {
  // ── 序章 / 起始武器 ───────────────────────────────────────
  iron_sword: {
    id:          'iron_sword',
    name:        '破舊鐵劍',
    tier:        'P',
    ATK:         0,
    hit:         0,
    tierSteps: {
      '100_80': 0,
      '79_60':  -1,
      '59_30':  -3,
      '30_0':   -6,
    },
    description: '序章教學武器，毫不起眼的鐵劍，卻是她走向戰場的第一步。',
  },

  // ── Tier A 武器（第 1–3 章）───────────────────────────────
  moon_kunai: {
    id:          'moon_kunai',
    name:        '月牙苦無',
    tier:        'A',
    ATK:         2,
    hit:         14,
    AGI:         5,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '輕巧的月牙形苦無，速度極快，適合先發制人。',
  },
  thorn_whip: {
    id:          'thorn_whip',
    name:        '血荊鞭',
    tier:        'A',
    ATK:         5,
    hit:         6,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '荊棘編成的皮鞭，攻擊範圍廣，造成持續撕裂傷。',
  },
  rune_hammer: {
    id:          'rune_hammer',
    name:        '符文重錘',
    tier:        'A',
    ATK:         7,
    hit:         2,
    WIL:         3,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '刻有古老符文的沉重鐵錘，揮出時意志之力隨之爆發。',
  },
  steel_blade: {
    id:          'steel_blade',
    name:        '鋼刃',
    tier:        'A',
    ATK:         4,
    hit:         5,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '鍛造精良的標準戰鬥刃，重量均衡，易於掌控。',
  },
  swift_dagger: {
    id:          'swift_dagger',
    name:        '疾風匕首',
    tier:        'A',
    ATK:         2,
    hit:         12,
    AGI:         3,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '輕巧短刃，犧牲攻擊力換取絕佳的速度加成。',
  },
  covenant_rod: {
    id:          'covenant_rod',
    name:        '契約法杖',
    tier:        'A',
    ATK:         3,
    hit:         8,
    maxSP:       15,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '注入靈力的法杖，提升 SP 上限，適合技能型戰鬥風格。',
  },

  // ── Tier B 武器（第 4–7 章）───────────────────────────────
  twin_blades: {
    id:          'twin_blades',
    name:        '裂隙雙刃',
    tier:        'B',
    ATK:         11,
    hit:         10,
    AGI:         4,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '一對以裂隙金屬鑄造的短刃，雙手並用時攻擊節奏難以預測。',
  },
  cursed_flail: {
    id:          'cursed_flail',
    name:        '詛咒連枷',
    tier:        'B',
    ATK:         13,
    hit:         5,
    drPen:       12,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '鑲嵌詛咒核心的連枷，攻擊帶有穿甲詛咒，護甲抵抗力下降。',
  },
  shadow_bow: {
    id:          'shadow_bow',
    name:        '影弓',
    tier:        'B',
    ATK:         7,
    hit:         18,
    AGI:         6,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '以暗影晶絲製成的弓，箭矢幾乎無聲，命中率驚人。',
  },
  soul_staff: {
    id:          'soul_staff',
    name:        '魂縛法杖',
    tier:        'B',
    ATK:         6,
    hit:         8,
    maxSP:       25,
    WIL:         5,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '封印了魂魄碎片的法杖，持有者靈力儲量大幅擴張。',
  },
  demon_fang: {
    id:          'demon_fang',
    name:        '惡魔之牙',
    tier:        'B',
    ATK:         10,
    hit:         8,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '以裂隙魔物之牙鑄成，散發著隱約的腐敗氣息，攻擊力驚人。',
  },
  rift_lance: {
    id:          'rift_lance',
    name:        '裂隙穿刺槍',
    tier:        'B',
    ATK:         8,
    hit:         15,
    drPen:       15,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '細長槍身可穿透護甲縫隙，對高 DR 目標效果額外提升 15%。',
  },
  spirit_blade: {
    id:          'spirit_blade',
    name:        '靈魂刃',
    tier:        'B',
    ATK:         9,
    hit:         10,
    WIL:         4,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '刀身帶有微弱的靈力脈動，強化意志，抵抗控制效果。',
  },

  // ── Tier C 武器（第 8–10 章）─────────────────────────────
  heaven_sword: {
    id:          'heaven_sword',
    name:        '天裂神劍',
    tier:        'C',
    ATK:         22,
    hit:         12,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '據說能斬裂天際的神器，攻擊力達到人類兵器的極限。',
  },
  hellfire_twin: {
    id:          'hellfire_twin',
    name:        '獄炎雙刀',
    tier:        'C',
    ATK:         18,
    hit:         15,
    drPen:       20,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '獄火鑄就的雙刀，每一擊都帶著穿透一切防禦的灼熱。',
  },
  void_scythe: {
    id:          'void_scythe',
    name:        '虛空鐮刀',
    tier:        'C',
    ATK:         16,
    hit:         8,
    maxSP:       20,
    WIL:         10,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '自虛空裂縫中取出的鐮刀，收割靈力的同時強化持有者意志。',
  },
  abyss_sword: {
    id:          'abyss_sword',
    name:        '深淵巨劍',
    tier:        'C',
    ATK:         20,
    hit:         5,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '從深淵裂隙中挖掘的神秘巨劍，攻擊力超凡，但耐久損耗極快。',
  },
  ruya_shadow_blade: {
    id:          'ruya_shadow_blade',
    name:        '瑠夜・縛影刃',
    tier:        'C',
    ATK:         15,
    hit:         20,
    WIL:         8,
    locked:      true,
    unlockCond:  'demon_a_trust_70',
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '瑠夜以契約之力鑄造，如暗影般寂靜，封印力量灌注其中。',
  },
  soga_war_axe: {
    id:          'soga_war_axe',
    name:        '颯牙・戰鬼戰斧',
    tier:        'C',
    ATK:         25,
    hit:         0,
    locked:      true,
    unlockCond:  'demon_b_trust_70',
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '颯牙的戰意凝聚而成，粗獷霸道，爆發力無與倫比。',
  },
  xuanming_cursed_staff: {
    id:          'xuanming_cursed_staff',
    name:        '玄冥・詛咒杖',
    tier:        'C',
    ATK:         12,
    hit:         10,
    maxSP:       30,
    drPen:       25,
    locked:      true,
    unlockCond:  'demon_c_trust_70',
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '玄冥詛咒的結晶，持有者的攻擊附帶穿透防禦的腐蝕之力。',
  },
}

/**
 * 取得武器資料
 * @param {string} weaponId
 * @returns {object|null}
 */
export function getWeaponData(weaponId) {
  return WEAPON_DB[weaponId] ?? null
}

export default WEAPON_DB