/**
 * WeaponDB — 武器資料庫
 * 武器影響 ATK 加成、命中率，並有耐久度系統
 */

const WEAPON_DB = {
  // ── 序章 / 起始武器 ───────────────────────────────────────
  iron_sword: {
    id:          'iron_sword',
    name:        '初探者舊鐵刃',
    tier:        'P',
    ATK:         0,
    hit:         0,
    tierSteps: {
      '100_80': 0,
      '79_60':  -1,
      '59_30':  -3,
      '30_0':   -6,
    },
    description: '某個在裂隙中消失的前人留下的鐵劍，刃面有使用痕跡，主人的名字已無從查明。有時在特定地點，刃面的磨損紋路會因共鳴而輕微發光——那是它的前主人曾站在同一個地方。',
  },

  // ── Tier A 武器（第 1–3 章）───────────────────────────────
  moon_kunai: {
    id:          'moon_kunai',
    name:        '月相刻苦無',
    tier:        'A',
    ATK:         2,
    hit:         14,
    AGI:         5,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '以月相週期為模型設計的投擲型短刃，內部有月光礦石粉末，在黑暗環境中會輕微發光。速度極快，適合在裂隙昏暗地帶的先制攻擊。',
  },
  thorn_whip: {
    id:          'thorn_whip',
    name:        '古荊痛訊鞭',
    tier:        'A',
    ATK:         5,
    hit:         6,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '以不知名古代植物的蔓莖製成，荊棘已成化石但仍保有原植物「想要攀附」的記憶。每次撕裂都傳遞這個記憶，讓傷口的痛感格外強烈。',
  },
  rune_hammer: {
    id:          'rune_hammer',
    name:        '古語銘文重錘',
    tier:        'A',
    ATK:         7,
    hit:         2,
    WIL:         3,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '錘面刻有失傳語言，目前只知其中包含「重量」和「穿越」兩個概念的片語。揮動時意志力隨之爆發，推測是符文在回應使用者的信念。',
  },
  steel_blade: {
    id:          'steel_blade',
    name:        '中性精鑄刃',
    tier:        'A',
    ATK:         4,
    hit:         5,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '設計上沒有任何特化，純粹追求基礎性能的均衡極致。沒有可被針對的特性，在裂隙環境中反而是難得的優點。',
  },
  swift_dagger: {
    id:          'swift_dagger',
    name:        '速相切換匕首',
    tier:        'A',
    ATK:         2,
    hit:         12,
    AGI:         3,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '刃面施加了讓空氣阻力接近零的處理，使刃速可超越正常物理範疇。犧牲傷害換取的速度加成，在先制判定和迴避方面均有顯著貢獻。',
  },
  covenant_rod: {
    id:          'covenant_rod',
    name:        '初階靈力導杖',
    tier:        'A',
    ATK:         3,
    hit:         8,
    maxSP:       15,
    tierSteps: { '100_80': 0, '79_60': -1, '59_30': -3, '30_0': -6 },
    description: '內部有細管連接頂端和握柄，讓靈力流通時有明確的路徑可循。SP上限的提升是因為導管同時與使用者的靈力儲存空間產生共鳴，物理擴張了其容量邊界。',
  },

  // ── Tier B 武器（第 4–7 章）───────────────────────────────
  twin_blades: {
    id:          'twin_blades',
    name:        '縫隙金屬雙刃',
    tier:        'B',
    ATK:         11,
    hit:         10,
    AGI:         4,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '以裂隙邊緣採集的金屬製成，金屬的晶格結構異常，打擊時的振動頻率難以被生物感知系統預測，這就是攻擊節奏「難以預測」的物理原因。',
  },
  cursed_flail: {
    id:          'cursed_flail',
    name:        '鍵結破壞詛枷',
    tier:        'B',
    ATK:         13,
    hit:         5,
    drPen:       12,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '鑲嵌的詛咒核心是能定向切斷化學鍵的礦石結晶，攻擊時選擇性破壞裝甲材料的分子鍵結，物理上降低護甲的整合性。',
  },
  shadow_bow: {
    id:          'shadow_bow',
    name:        '暗晶絲射弓',
    tier:        'B',
    ATK:         7,
    hit:         18,
    AGI:         6,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '弦材使用深淵暗晶絲，不反射光線，振動頻率落在次聲波範圍，人耳無法感知。目標在聽到弓弦聲之前已被命中。',
  },
  soul_staff: {
    id:          'soul_staff',
    name:        '魂碎封存法杖',
    tier:        'B',
    ATK:         6,
    hit:         8,
    maxSP:       25,
    WIL:         5,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '以封印術固定了若干靈魂碎片在杖身中，來源無法確認。持有者靈力儲量擴張，偶爾能聽到杖身傳出模糊的低語聲。',
  },
  demon_fang: {
    id:          'demon_fang',
    name:        '深淵存在遺牙刃',
    tier:        'B',
    ATK:         10,
    hit:         8,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '以深淵存在脫落的齒牙改造而成，攻擊帶有輕微的「侵蝕存在連貫性」效果，令受傷部位的感知暫時混亂。',
  },
  rift_lance: {
    id:          'rift_lance',
    name:        '縫隙導引穿刺槍',
    tier:        'B',
    ATK:         8,
    hit:         15,
    drPen:       15,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '槍尖設計遵循裂隙形成時的幾何原理，自動尋找護甲縫隙的最優路徑。對高 DR 目標的穿透加成來自此設計原理的實際效果。',
  },
  spirit_blade: {
    id:          'spirit_blade',
    name:        '靈脈共鳴刃',
    tier:        'B',
    ATK:         9,
    hit:         10,
    WIL:         4,
    tierSteps: { '100_80': 0, '79_60': -2, '59_30': -5, '30_0': -9 },
    description: '刃身帶有與持有者靈力脈動同步的細微振動，同時強化攻擊和意志防禦。持有者在無意識中將部分意志力外化到刃身，形成雙向的防禦層。',
  },

  // ── Tier C 武器（第 8–10 章）─────────────────────────────
  heaven_sword: {
    id:          'heaven_sword',
    name:        '越層切割神劍',
    tier:        'C',
    ATK:         22,
    hit:         12,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '能切割空間法則本身的神器，攻擊的對象並非目標的物質，而是目標「存在於此空間」的合法性。斬出後，空氣在癒合前有短暫的完全靜止。',
  },
  hellfire_twin: {
    id:          'hellfire_twin',
    name:        '下層炎能雙刀',
    tier:        'C',
    ATK:         18,
    hit:         15,
    drPen:       20,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '以深淵下層的「炎能」凝固而成——不是火，而是某種能量的熱化形態，接觸物質時解除其材料的防禦鍵結。',
  },
  void_scythe: {
    id:          'void_scythe',
    name:        '真空收割鐮刀',
    tier:        'C',
    ATK:         16,
    hit:         8,
    maxSP:       20,
    WIL:         10,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '從真正的虛空裂縫中取出，曾存在於沒有任何物質的空間並記憶了那個空間。攻擊時短暫在目標周圍創造局部真空壓力差。',
  },
  abyss_sword: {
    id:          'abyss_sword',
    name:        '淵底採掘巨劍',
    tier:        'C',
    ATK:         20,
    hit:         5,
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '從深淵最深處挖掘的礦石直接鑄成，幾乎未經加工——原材料的形狀本就接近適合持握的比例，這一點至今無法解釋。材料的內部應力使其自我消耗速度極快，像是它仍試圖回到最深的地方。',
  },
  ruya_shadow_blade: {
    id:          'ruya_shadow_blade',
    name:        '瑠夜・縛影鑄刃',
    tier:        'C',
    ATK:         15,
    hit:         20,
    WIL:         8,
    locked:      true,
    unlockCond:  'demon_a_trust_70',
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '瑠夜以自身的封印之力鑄造，刃身幾乎不反射任何光線。攻擊時在目標的感知層中留下「此處沒有危險」的錯誤信號，使命中率大幅提升——那是瑠夜最習慣的手法：讓對方先放鬆，再收緊。',
  },
  soga_war_axe: {
    id:          'soga_war_axe',
    name:        '颯牙・戰意鑄斧',
    tier:        'C',
    ATK:         25,
    hit:         0,
    locked:      true,
    unlockCond:  'demon_b_trust_70',
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '颯牙積累的戰意在某個瞬間自發凝固成型，既非鑄造亦非鍛打。粗獷霸道的造型是戰意本身的形狀，每次揮動都在釋放凝固其中的那一瞬間的全部戰意——直接、沒有任何修飾。',
  },
  xuanming_cursed_staff: {
    id:          'xuanming_cursed_staff',
    name:        '玄冥・腐蝕詛杖',
    tier:        'C',
    ATK:         12,
    hit:         10,
    maxSP:       30,
    drPen:       25,
    locked:      true,
    unlockCond:  'demon_c_trust_70',
    tierSteps: { '100_80': 0, '79_60': -3, '59_30': -7, '30_0': -12 },
    description: '玄冥長年研究腐蝕詛咒的結晶，杖身材料已被詛咒力量完全浸透。每次攻擊時自動計算目標防禦的鍵結弱點並定向施加壓力——不多說，直接解決。',
  },
}

/**
 * 取得武器資料
 * @param {string} weaponId
 * @returns {object|null}
 */
export function getWeaponData(weaponId) {
  return WEAPON_DB[weaponId] ?? null
}

export default WEAPON_DB
